services:
 postgres:
    image: postgres:latest
    container_name: localdevpgs
    environment:
      POSTGRES_USER: localdev
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: localdev
    ports:
      - "5432:5432"
